=== AlexAbak/deneb/xml/Notation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://deneblingvo.org/Notation/1.0" xmlns:tns="http://deneblingvo.org/Notation/1.0" elementFormDefault="qualified">
    <complexType name="notation">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="definition" type="tns:definition"></element>
    	</sequence>
    	<attribute name="lang" type="string"></attribute>
    </complexType>
    <element name="notation" type="tns:notation"></element>

    <complexType name="definition">
   		<choice>
   			<element name="string" type="tns:string"></element>
   			<element name="characters" type="tns:characters"></element>
   			<element name="choice" type="tns:choice"></element>
   			<element name="repeat" type="tns:repeat"></element>
   			<element name="list" type="tns:list"></element>
   			<element name="lexeme" type="tns:lexeme"></element>
   		</choice>
   		<attribute name="lexeme" type="string"></attribute>
    </complexType>
    
    <complexType name="string">
    	<attribute name="value" type="string"></attribute>
    </complexType>
    
    <complexType name="characters">
    	<attribute name="min" type="string"></attribute>
    	<attribute name="max" type="string"></attribute>
    </complexType>

    <complexType name="choice">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="lexeme" type="tns:lexeme"></element>
    	</sequence>
    </complexType>
    
    <complexType name="repeat">
    	<sequence>
    		<element name="ranges" type="tns:ranges"></element>
    		<element name="body" type="tns:body"></element>
    		<element name="glue" type="tns:glue"></element>
    	</sequence>
    	<attribute name="generosity" type="string"></attribute>
    </complexType>

    <complexType name="lexeme">
    	<attribute name="name" type="string"></attribute>
    	<attribute name="ignore" type="string"></attribute>
    </complexType>

    <complexType name="ranges">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="range" type="tns:range"></element>
    	</sequence>
    </complexType>

    <complexType name="body">
    	<sequence minOccurs="0" maxOccurs="1">
    		<element name="lexeme" type="tns:lexeme"></element>
    	</sequence>
    </complexType>
    
    <complexType name="glue">
    	<sequence minOccurs="0" maxOccurs="1">
    		<element name="lexeme" type="tns:lexeme"></element>
    	</sequence>
    </complexType>

    <complexType name="range">
    	<attribute name="min" type="string"></attribute>
    	<attribute name="max" type="string"></attribute>
    </complexType>

    <complexType name="list">
    	<sequence minOccurs="1" maxOccurs="unbounded">
    		<element name="lexeme" type="tns:lexeme"></element>
    	</sequence>
    </complexType>
</schema>

=== AlexAbak/deneb/xml/Notation.xml
<?xml version="1.0" encoding="utf-8"?>
<den:notation lang="" xmlns:den="http://deneblingvo.org/xsd/notation/1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://deneblingvo.org/xsd/notation/1.0 notation.xsd">
  <den:definition lexeme="Нотация">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="0" max="0"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="ЭлементНотации" ignore="false"/>
      </den:body>
      <den:glue/>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="ЭлементНотации">
    <den:choice>
      <den:lexeme name="ОпределениеЛексемы" ignore="false"/>
      <den:lexeme name="Комментарий" ignore="false"/>
      <den:lexeme name="Пробел" ignore="true"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="ОпределениеЛексемы">
    <den:list>
      <den:lexeme name="Лексема" ignore="false"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="НачалоОпределения" ignore="true"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="Определение" ignore="false"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="ОкончаниеОпределения" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="Комментарий">
    <den:choice>
      <den:lexeme name="ОднострочныйКомментарий" ignore="false"/>
      <den:lexeme name="МногострочныйКомментарий" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="Пробел">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="0" max="0"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="ПробельныйСимвол" ignore="false"/>
      </den:body>
      <den:glue/>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="Лексема">
    <den:list>
      <den:lexeme name="МеткаИсключеннойЛексемы" ignore="false"/>
      <den:lexeme name="ИмяЛексемы" ignore="false"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="НачалоОпределения">
    <den:string value=":="/>
  </den:definition>
  <den:definition lexeme="Определение">
    <den:choice>
      <den:lexeme name="Выбор" ignore="false"/>
      <den:lexeme name="Список" ignore="false"/>
      <den:lexeme name="Повторение" ignore="false"/>
      <den:lexeme name="Лексема" ignore="false"/>
      <den:lexeme name="Символы" ignore="false"/>
      <den:lexeme name="Строка" ignore="false"/>
      <den:lexeme name="РегулярноеВыражение" ignore="false"/>
      <den:lexeme name="Блок" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="ОкончаниеОпределения">
    <den:string value=";"/>
  </den:definition>
  <den:definition lexeme="ОднострочныйКомментарий">
    <den:list>
      <den:lexeme name="НачалоОднострочногоКомментария" ignore="true"/>
      <den:lexeme name="ЛюбыеСимволы" ignore="false"/>
      <den:lexeme name="ОкончаниеОднострочногоКомментария" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="МногострочныйКомментарий">
    <den:list>
      <den:lexeme name="НачалоМногострочногоКомментария" ignore="true"/>
      <den:lexeme name="ЛюбыеСимволы" ignore="false"/>
      <den:lexeme name="ОкончаниеМногострочногоКомментария" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="ПробельныйСимвол">
    <den:choice>
      <den:lexeme name="СимволПробела" ignore="false"/>
      <den:lexeme name="СимволТабуляции" ignore="false"/>
      <den:lexeme name="СимволВозвратаКаретки" ignore="false"/>
      <den:lexeme name="СимволПереносаСтроки" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="МеткаИсключеннойЛексемы">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="0" max="1"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="ИсключеннаяЛексема" ignore="false"/>
      </den:body>
      <den:glue/>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="ИмяЛексемы">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="1" max="0"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="СимволЛексемы" ignore="false"/>
      </den:body>
      <den:glue/>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="Выбор">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="2" max="0"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="Вариант" ignore="false"/>
      </den:body>
      <den:glue>
        <den:lexeme name="ПолныйРазделительВыбора" ignore="true"/>
      </den:glue>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="Список">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="2" max="0"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="Пункт" ignore="false"/>
      </den:body>
      <den:glue>
        <den:lexeme name="Пробел" ignore="true"/>
      </den:glue>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="Повторение">
    <den:list>
      <den:lexeme name="Элемент" ignore="false"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="МеткаЩедрости" ignore="false"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="Количество" ignore="false"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="Символы">
    <den:list>
      <den:lexeme name="НачалоСимвола" ignore="true"/>
      <den:lexeme name="Литерал" ignore="false"/>
      <den:lexeme name="ОкончаниеСимвола" ignore="true"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="РазделительДиапазона" ignore="true"/>
      <den:lexeme name="Пробел" ignore="true"/>
      <den:lexeme name="НачалоСимвола" ignore="true"/>
      <den:lexeme name="Литерал" ignore="false"/>
      <den:lexeme name="ОкончаниеСимвола" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="Строка">
    <den:list>
      <den:lexeme name="НачалоСтроки" ignore="true"/>
      <den:lexeme name="Литералы" ignore="false"/>
      <den:lexeme name="ОкончаниеСтроки" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="РегулярноеВыражение">
    <den:list>
      <den:lexeme name="МеткаРегулярногоВыражения" ignore="true"/>
      <den:lexeme name="НачалоСтроки" ignore="true"/>
      <den:lexeme name="Литералы" ignore="false"/>
      <den:lexeme name="ОкончаниеСтроки" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="Блок">
    <den:list>
      <den:lexeme name="НачалоБлока" ignore="true"/>
      <den:lexeme name="Определение" ignore="false"/>
      <den:lexeme name="ОкончаниеБлока" ignore="true"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="НачалоОднострочногоКомментария">
    <den:string value="//"/>
  </den:definition>
  <den:definition lexeme="ЛюбыеСимволы">
    <den:repeat generosity="true">
      <den:ranges>
        <den:range min="0" max="0"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="ЛюбойСимвол" ignore="false"/>
      </den:body>
      <den:glue/>
    </den:repeat>
  </den:definition>
  <den:definition lexeme="ОкончаниеОднострочногоКомментария">
    <den:choice>
      <den:lexeme name="ПереносСтроки" ignore="false"/>
      <den:lexeme name="СимволВозвратаКаретки" ignore="false"/>
      <den:lexeme name="СимволПереносаСтроки" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="НачалоМногострочногоКомментария">
    <den:string value="/*"/>
  </den:definition>
  <den:definition lexeme="ОкончаниеМногострочногоКомментария">
    <den:string value="*/"/>
  </den:definition>
  <den:definition lexeme="СимволПробела">
    <den:string value=" "/>
  </den:definition>
  <den:definition lexeme="СимволТабуляции">
    <den:string value="&#9;"/>
  </den:definition>
  <den:definition lexeme="СимволВозвратаКаретки">
    <den:string value="&#13;"/>
  </den:definition>
  <den:definition lexeme="СимволПереносаСтроки">
    <den:string value="&#10;"/>
  </den:definition>
  <den:definition lexeme="ИсключеннаяЛексема">
    <den:string value="%"/>
  </den:definition>
  <den:definition lexeme="СимволЛексемы">
    <den:characters min="1024" max="1319"/>
  </den:definition>
  <den:definition lexeme="Вариант">
    <den:choice>
      <den:lexeme name="Список" ignore="false"/>
      <den:lexeme name="Повторение" ignore="false"/>
      <den:lexeme name="Лексема" ignore="false"/>
      <den:lexeme name="Символы" ignore="false"/>
      <den:lexeme name="Строка" ignore="false"/>
      <den:lexeme name="РегулярноеВыражение" ignore="false"/>
      <den:lexeme name="Блок" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="ПолныйРазделительВыбора">
    <den:list>
      <den:lexeme name="Пробел" ignore="false"/>
      <den:lexeme name="РазделительВыбора" ignore="false"/>
      <den:lexeme name="Пробел" ignore="false"/>
    </den:list>
  </den:definition>
  <den:definition lexeme="РазделительВыбора">
    <den:string value="/"/>
  </den:definition>
  <den:definition lexeme="Пункт">
    <den:choice>
      <den:lexeme name="Выбор" ignore="false"/>
      <den:lexeme name="Повторение" ignore="false"/>
      <den:lexeme name="Лексема" ignore="false"/>
      <den:lexeme name="Символы" ignore="false"/>
      <den:lexeme name="Строка" ignore="false"/>
      <den:lexeme name="РегулярноеВыражение" ignore="false"/>
      <den:lexeme name="Блок" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="Элемент">
    <den:choice>
      <den:lexeme name="Лексема" ignore="false"/>
      <den:lexeme name="Блок" ignore="false"/>
      <den:lexeme name="БлокПовторения" ignore="false"/>
    </den:choice>
  </den:definition>
  <den:definition lexeme="МеткаЩедрости">
    <den:repeat generosity="false">
      <den:ranges>
        <den:range min="0" max="1"/>
      </den:ranges>
      <den:body>
        <den:lexeme name="Щедрость" ignore="false"/>
      </den:body>
