=== AlexAbak/deneb/transformation/xml/test/Example.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://deneblingvo.org/xsd/transformator/Example/1.0" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0">

    <xs:element name="database" type="exm:database"></xs:element>
    
    <xs:complexType name="database">
    	<xs:sequence>
    		<xs:element name="table" type="exm:table" minOccurs="0" maxOccurs="unbounded">
    		</xs:element>
    	</xs:sequence>
    </xs:complexType>

    <xs:complexType name="table">
    	<xs:sequence>
    		<xs:element name="field" type="exm:field" minOccurs="0" maxOccurs="unbounded">
    		</xs:element>
    	</xs:sequence>
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="field">
    	<xs:attribute name="name" type="xs:string"></xs:attribute>
    	<xs:attribute name="type" type="xs:string"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== AlexAbak/deneb/transformation-test/xml/test/result.xml
<?xml version="1.0" encoding="UTF-8"?>
<exm:database xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://deneblingvo.org/xsd/transformator/Example/1.0 Example.xsd">
   <exm:table xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
              name="TABLE1">
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="K_ID"
                 type="NUMBER(32)"/>
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="F_VALUE1"
                 type="VARCHAR"/>
	  </exm:table>
   <exm:table xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
              name="TABLE2">
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="K_ID"
                 type="NUMBER(32)"/>
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="F_VALUE2"
                 type="VARCHAR"/>
	  </exm:table>
   <exm:table xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
              name="TABLE3">
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="K_ID"
                 type="NUMBER(32)"/>
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="F_VALUE3"
                 type="VARCHAR"/>
	  </exm:table>
   <exm:table xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
              name="TABLE4">
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="K_ID"
                 type="NUMBER(32)"/>
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="F_VALUE4"
                 type="VARCHAR"/>
	  </exm:table>
   <exm:table xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
              name="TABLE5">
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="K_ID"
                 type="NUMBER(32)"/>
		    <exm:field xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0"
                 name="F_VALUE5"
                 type="VARCHAR"/>
	  </exm:table>
</exm:database>

=== AlexAbak/deneb/transformation/xml/test/result.xml
<?xml version="1.0" encoding="UTF-8"?><exm:database xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:exm="http://deneblingvo.org/xsd/transformator/Example/1.0" xsi:schemaLocation="http://deneblingvo.org/xsd/transformator/Example/1.0 Example.xsd"><exm:table name="TABLE1">
		<exm:field name="K_ID" type="NUMBER(32)"/>
		<exm:field name="F_VALUE1" type="VARCHAR"/>
	</exm:table><exm:table name="TABLE2">
		<exm:field name="K_ID" type="NUMBER(32)"/>
		<exm:field name="F_VALUE2" type="VARCHAR"/>
	</exm:table><exm:table name="TABLE3">
		<exm:field name="K_ID" type="NUMBER(32)"/>
		<exm:field name="F_VALUE3" type="VARCHAR"/>
	</exm:table><exm:table name="TABLE4">
		<exm:field name="K_ID" type="NUMBER(32)"/>
		<exm:field name="F_VALUE4" type="VARCHAR"/>
	</exm:table><exm:table name="TABLE5">
		<exm:field name="K_ID" type="NUMBER(32)"/>
		<exm:field name="F_VALUE5" type="VARCHAR"/>
	</exm:table></exm:database>
